version: "3.6"
services:
  object-injection:
    build: .
    restart: unless-stopped
    ports:
      - "12001:80"
    volumes:
      - ./src:/var/www/html/
    environment:
      - FLAG1=CBJS{FAKE_FLAG_FAKE_FLAG}
      - FLAG2=CBJS{FAKE_FLAG_FAKE_FLAG}
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=myDB
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password 
    volumes:
      - ./db/:/docker-entrypoint-initdb.d